_target_: src.models.mnist_gan_model.MNISTGANModel

lr: 0.0002
b1: 0.5
b2: 0.999
n_classes: 10
latent_dim: 100
channels: 1
img_size: 32

# TODO: instantiate the generator and discriminator objects with Hydra
#       https://hydra.cc/docs/advanced/instantiate_objects/overview/

generator:
  _target_: src.models.modules.generators.Generator
  latent_dim: ${model.latent_dim}
  img_size: ${model.img_size}
  channels: ${model.channels}
  n_classes: ${model.n_classes}

discriminator:
  _target_: src.models.modules.discriminators.Discriminator
  img_size: ${model.img_size}
  channels: ${model.channels}
  n_classes: ${model.n_classes}